### ISSUE TITLE
Prototype Issue

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/dannywaldman#1]
https://github.com/CodingDojo-MEAN-06-18/dannywaldman/blob/39982772a6156c13a7b6cdf5ea5b08a717b076ec/week1/bstdepth/index.html#L7-L20

Nice work on the BST algorithm. You probably don't want your Prototype methods nested inside your constructor function.

**Comment by dannywaldman** [comment]
Removed the prototype insert method from the constructor.
